image: maven:3.6.1-jdk-11

compilation:
  stage: build
  tags: 
    - tls
  script:
    - echo "Der Server wird gebaut"
    - mvn clean package -DskipTests=true

aufgabe0:
  stage: test
  tags: 
    - tls
  script:
    - mvn test -P aufgabe0

aufgabe1:
  stage: test
  tags: 
    - tls
  script:
    - if [ `date +%y%m%d` -gt 241016 ]; then mvn test -P aufgabe1; fi
    
aufgabe2:
  stage: test
  tags: 
    - tls
  script:
    - if [ `date +%y%m%d` -gt 241030 ]; then mvn test -P aufgabe2; fi

aufgabe3:
  stage: test
  tags: 
    - tls
  script:
    - if [ `date +%y%m%d` -gt 241113 ]; then mvn test -P aufgabe3; fi

aufgabe4:
  stage: test
  tags: 
    - tls
  script:
    - if [ `date +%y%m%d` -gt 241211 ]; then mvn test -P aufgabe4; fi

